# Copyright 2026 Rik Essenius
# Licensed under the Apache License, Version 2.0. See the LICENSE file for details.
# File: config.yaml

environment:
  logging:
    level: info
  paths:
    wal: wal.jsonl
    state: state.json
  timescaledb:
    host: localhost
    port: 5432
    ssl_mode: verify-ca
    db: finance
    max_batch_size: 1000
    max_batch_age_seconds: 2.0

business:
  providers:
    yahoo:
      timeout: 10s
      timezone: UTC
      constraints:
        history_limits:
          default: 60d
          1m: 7d
          60m: 730d
          1d: null
    
    ecb:
      timeout: 20s
      timezone: Europe/Berlin
      constraints: {}
    
    fred:
      timeout: 10s
      timezone: America/Chicago
      constraints: 
        rate_limit:
          # not used as way beyond usage, just capturing 
          requests_per_minute: 120

  series_templates:
    daily_value:
      interval: 1d
      series_type: value
      # for >=1d, default retention is long lived, bootstrap_history 10y
      # long lived means stored in table without retention policy

    daily_candle:
      interval: 1d
      # default series_type is candle

    intraday_value:
      interval: 5m
      series_type: value
      # for <1d, default retention is short lived, bootstrap_history 30d
      # short lived means stored in table with retention policy

    intraday_candle:
      interval: 5m
  
  assets:

    # -------------------------
    # FOREX: EURUSD (Yahoo)
    # -------------------------
    eurusd_yahoo:
      provider: 
        name: yahoo
        code: EURUSD=X
      symbol: EURUSD
      tags:
        instrument: forex
        exchange: FOREX
        region: GLOBAL
        currency: USD
        unit: ratio
      series:
        daily: daily_value

    # -------------------------
    # FOREX: EURUSD (ECB)
    # -------------------------
    eurusd_ecb:
      provider: ecb
      provider_code: USD_EUR
      symbol: EURUSD
      tags:
        instrument: forex
        exchange: FOREX
        region: EU
        currency: USD
        unit: ratio
      series:
        daily: daily_value

    # -------------------------
    # COMMODITIES
    # -------------------------
    gold:
      provider:
        name: yahoo
        code: GC=F
      symbol: GOLD
      tags:
        instrument: commodity
        exchange: COMMODITY
        region: GLOBAL
        currency: USD
        unit: troy_ounce
      series:
        intraday: intraday_candle
        daily: daily_candle

    wti:
      provider:
        name: yahoo
        code: CL=F
      symbol: WTI
      tags:
        instrument: commodity
        exchange: COMMODITY
        region: GLOBAL
        currency: USD
        unit: barrel
      series:
        intraday: intraday_candle
        daily: daily_candle

    brent:
      provider:
        name: yahoo
        code: BZ=F
      symbol: BRENT
      tags:
        instrument: commodity
        exchange: COMMODITY
        region: GLOBAL
        currency: USD
        unit: barrel
      series:
        intraday: intraday_candle
        daily: daily_candle

    # -------------------------
    # EQUITIES
    # -------------------------
    shell:
      symbol: SHEL
      provider:
        name: yahoo
        code: SHEL
      tags:
        instrument: equity
        exchange: NYSE
        region: GLOBAL
        currency: USD
        unit: share
      series:
        intraday: intraday_candle
        daily: daily_candle

    shell_as:
      provider:
        name: yahoo
        code: SHELL.AS
      symbol: SHELL.AS
      tags:
        instrument: equity
        exchange: EURONEXT
        region: GLOBAL
        currency: EUR
        unit: share
      series:
        intraday: intraday_candle
        daily: daily_candle

    # -------------------------
    # INDEXES
    # -------------------------
    spx:
      provider:
        name: yahoo
        code: ^GSPC
      symbol: SPX
      tags:
        instrument: index
        exchange: NYSE
        region: US
        currency: USD
        unit: index_point
      series:
        daily: daily_candle

    vix:
      provider:
        name: yahoo
        code: ^VIX
      symbol: VIX
      tags:
        instrument: index
        exchange: CBOE
        region: US
        currency: USD
        unit: index_point
      series:
        daily: daily_candle

    # -------------------------
    # CRYPTO
    # -------------------------
    bitcoin:
      provider:
        name: yahoo
        code: "BTC-USD"
      symbol: BTCUSD
      tags:
        instrument: crypto
        exchange: CRYPTO
        region: GLOBAL
        currency: USD
        unit: coin
      series:
        intraday: intraday_candle
        daily: daily_candle

    # -------------------------
    # MACRO (FRED + Treasury)
    # -------------------------
    fred_10y_nominal:
      provider: 
        name: fred
        code: DGS10
      symbol: 10Y_NOMINAL
      tags:
        instrument: macro
        region: US
        unit: percent
      series:
        daily: daily_value

    fred_10y_breakeven:
      provider:
        name: fred
        code: T10YIE
      symbol: 10Y_BREAKEVEN
      tags:
        instrument: macro
        region: US
        unit: percent
      series:
        daily: daily_value

    fed_balance_sheet:
      provider:
        name: fred
        code: WALCL
      symbol: BALANCE_SHEET
      tags:
        instrument: macro
        region: US
        unit: billions_usd
      series:
        daily: daily_value

   # treasury_avg:
   #   provider: treasury
   #   provider_code: avg_interest_rate
   #   symbol: AVG_INTEREST_RATE
   #   tags:
   #     instrument: macro
   #     region: US
   #     unit: percent
   #     provider: treasury
   #   series:
   #     daily:
   #       interval: 1d

  # -------------------------
  # COMPOSITES
  # note: disabled in V1
  # -------------------------
  composites:
    10Y_REAL:
      expression: "fred_10y_nominal - fred_10y_breakeven"
      symbol: 10Y_REAL
      series: daily
      tags:
        instrument: macro
        region: US
        unit: percent

    GOLD_DAILY_RANGE:
      expression: "gold.high - gold.low"
      symbol: GOLD_DAILY_RANGE
      series: daily
      tags:
        instrument: commodity
        region: GLOBAL
        unit: USD
