# Copyright 2026 Rik Essenius
# Licensed under the Apache License, Version 2.0. See the LICENSE file for details.
# File: config.yaml

environment:
  logging:
    level: info
  paths:
    wal: wal.jsonl
  timescaledb:
    host: localhost
    port: 5432
    ssl_mode: verify-full
    db: finance
    max_batch_size: 1000
    max_batch_age_seconds: 2.0

business:
  providers:
    yahoo:
      timeout: 10s
      sweep:
        default:
          window: 2h
          cadence: 30m
        1d:
          window: 1w
          cadence: 1d
      constraints:
        history_limits:
          default: 1w
          5m: 60d
          1h: 730d
          1d: null

    ecb:
      timeout: 20s
      overlap:
        default:
          window: 0
      constraints: {}

    fred:
      api_key_required: true
      timeout: 10s
      sweep:
        default:
          window: 30d
          cadence: 1w
      constraints:
        rate_limit:
          # not used, as way beyond usage. Just capturing
          requests_per_minute: 120

  templates:

    daily:
      interval: 1d
      # default puplication_offset is same as interval
      # for >=1d, default retention is long lived, bootstrap_history 10y
      # long lived means stored in table without retention policy

    intraday:
      interval: 5m
      # retention period is defined in the database. Keep aligned.
      retention_period: 30d
      # for <1d, default retention is short lived, bootstrap_history 30d
      # short lived means stored in table with retention policy

    candle: {}
      # default series_type is candle

    value:
      series_type: value
      # values are usually published entities like the daily EUR/USR rate of ECB or FRED interest rates.
      # So, we don't need to wait for the next day to fetch them.

    # Calendar templates.
    # Default: week_start=mon, week_end=fri, timezone UTC, market open min, market_close max (i.e. 24x5)
    # These defaults are applied in the calendar and are not saved in the database

    24x7:
      week_start: sun
      week_end: sat
      market_open: min
      market_close: max

    24x5:
      market_open: min
      market_close: max

    us_treasury:
      timezone: America/New_York
      # you can also use different metadata in templates
      instrument: MACRO
      region: US

    ecb:
      timezone: Europe/Berlin
      publication_offset: 16h
      market_open: 15:55
      market_close: 16:05

  assets:

    # -------------------------
    # FOREX: EURUSD (Yahoo)
    # -------------------------

    # With yahoo, most metadata is grabbed from the response. Configuration here will override that.
    # What minimally remains is the provider, the provider code and a series.
    # Since Yahoo doesn't return region and unit, those should be provided here too.

    eurusd_yahoo:
      provider:
        name: yahoo
        code: EURUSD=X
      symbol: EURUSD
      region: GLOBAL
      unit: EUR
      series:
        daily: daily

    # -------------------------
    # FOREX: EURUSD (ECB)
    # -------------------------

    eurusd_ecb:
      provider:
        name: ecb
        code: USD_EUR
      symbol: EURUSD
      long_name: daily EUR/USD rate
      templates: ecb
      instrument: FOREX
      exchange: ECB
      region: EU
      currency: USD
      unit: ratio
      series:
        daily: [daily, value, ecb]

    # -------------------------
    # COMMODITIES
    # -------------------------

    gold:
      provider:
        name: yahoo
        code: GC=F
      templates: 24x7
      region: GLOBAL
      unit: 100_troy_ounce
      series:
        intraday: intraday
        daily: daily

    wti:
      provider:
        name: yahoo
        code: CL=F
      region: GLOBAL
      unit: barrel
      series:
        intraday: intraday
        daily: daily

    brent:
      provider:
        name: yahoo
        code: BZ=F
      region: GLOBAL
      unit: barrel
      series:
        intraday: intraday
        daily: daily

    # -------------------------
    # EQUITIES
    # -------------------------

    shell:
      provider:
        name: yahoo
        code: SHEL
      region: UK
      unit: share
      series:
        intraday: intraday
        daily: daily

    # -------------------------
    # ETFs / ETCs
    # -------------------------

    # iShares Physical Gold ETC
    ppfb:
      provider:
        name: yahoo
        code: PPFB.DE
      region: WORLD
      unit: share
      series:
        intraday: intraday
        daily: daily

    # Vanguard FTSE All-World UCITS
    vwce:
      provider:
        name: yahoo
        code: VWCE.AS
      region: WORLD
      unit: share
      series:
        intraday: intraday
        daily: daily

    # -------------------------
    # INDEXES
    # -------------------------

    spx:
      provider:
        name: yahoo
        code: ^GSPC
      region: US
      unit: index_point
      series:
        daily: daily

    vix:
      provider:
        name: yahoo
        code: ^VIX
      region: US
      unit: index_point
      series:
        daily: daily

    # -------------------------
    # CRYPTO
    # -------------------------

    bitcoin:
      provider:
        name: yahoo
        code: "BTC-USD"
      symbol: BTCUSD
      templates: 24x7
      region: GLOBAL
      unit: coin
      series:
        intraday: intraday
        daily: daily

    # -------------------------
    # MACRO (FRED + Treasury)
    # -------------------------

    fred_10y_nominal:
      provider:
        name: fred
        code: DGS10
      long_name: Market Yield on U.S. Treasury Securities at 10-Year Constant Maturity, Quoted on an Investment Basis
      first_available_date: 1962-01-02
      symbol: 10Y_NOMINAL
      templates: us_treasury
      unit: percent
      series:
        daily: [daily, value]

    fred_10y_breakeven:
      provider:
        name: fred
        code: T10YIE
      long_name: 10-Year Breakeven Inflation Rate
      first_available_date: 1982-01-04
      symbol: 10Y_BREAKEVEN
      templates: us_treasury
      unit: percent
      series:
        daily: [daily, value]

    fed_balance_sheet:
      provider:
        name: fred
        code: WALCL
      symbol: BALANCE_SHEET
      long_name: "Assets: Total Assets: Total Assets (Less Eliminations from Consolidation): Wednesday Level"
      first_available_date: 2002-12-18
      templates: us_treasury
      unit: Millions of U.S. Dollars
      series:
        daily: [daily, value]
