# Copyright 2026 Rik Essenius
# Licensed under the Apache License, Version 2.0. See the LICENSE file for details.
# File: config_test.yaml

environment:
  logging:
    level: debug
  paths:
    wal: wal.jsonl
  timescaledb:
    host: localhost
    port: 5433
    ssl_mode: verify-full
    db: test
    max_batch_size: 1000
    max_batch_age_seconds: 2.0

business:
  providers:
    yahoo:
      timeout: 10s
      sweep: 
        default: 
          window: 2h
          cadence: 30m
        1d: 
          window: 1w
          cadence: 1d
      constraints:
        history_limits:
          default: 1w
          5m: 60d
          1h: 730d
          1d: null
    
    ecb:
      timeout: 20s
      overlap:
        default:
          window: 0
      constraints: {}

    fred:
      timeout: 10s
      sweep: 
        default: 
          window: 30d
          cadence: 1w
      constraints: 
        rate_limit:
          # not used as way beyond usage, just capturing 
          requests_per_minute: 120

  templates:

    daily:
      interval: 1d
      # default puplication_offset is same as interval
      # for >=1d, default retention is long lived, bootstrap_history 10y
      # long lived means stored in table without retention policy

    intraday:
      interval: 5m
      # retention period is defined in the database. Keep aligned.
      retention_period: 30d
      # for <1d, default retention is short lived, bootstrap_history 30d
      # short lived means stored in table with retention policy

    candle: {}
      # default series_type is candle

    value:
      series_type: value
      # values are usually published entities like the daily EUR/USR rate of ECB or FRED interest rates.
      # So, we don't need to wait for the next day to fetch them.

    # Calendar templates. 
    # Default: week_start=mon, week_end=fri, timezone UTC, market open min, market_close max (i.e. 24x5)

    24x7:
      week_start: sun
      week_end: sat
      market_open: min
      market_close: max

    24x5: {}
      # defaults are correct

    eu_equities:
      timezone: Europe/Amsterdam
      market_open: 9:00
      market_close: 17:30

    us_equities:
      timezone: America/New_York
      market_open: 09:30
      market_close: 16:00

    cboe_equities:
      timezone: America/Chicago
      market_open: 8:30
      market_close: 15:00

    cme_futures:
      timezone: America/Chicago
      market_open: 17:00
      market_close: 16:00  # next day, with daily maintenance break

    us_treasury:
      timezone: America/New_York

    us_commodities:
      timezone: America/New_York
      week_start: sun
      week_end: sat

    new_york:
      timezone: America/New_York
    
    london:
      timezone: Europe/London

    ecb:
      timezone: Europe/Berlin
      publication_offset: 16h
      market_open: 15:55
      market_close: 16:05

  assets:

    # -------------------------
    # FOREX: EURUSD (Yahoo)
    # -------------------------
    eurusd_yahoo:
      provider: 
        name: yahoo
        code: EURUSD=X
      symbol: EURUSD
      tags:
        region: GLOBAL
        unit: 1 EUR
      series:
        daily: daily

    # -------------------------
    # FOREX: EURUSD (ECB)
    # -------------------------
    eurusd_ecb:
      provider:
        name: ecb
        code: USD_EUR
      symbol: EURUSD
      metadata: ecb
      tags:
        instrument: forex
        exchange: FOREX
        region: EU
        currency: USD
        unit: ratio
      series:
        daily: [daily, value, ecb]

    # -------------------------
    # COMMODITIES
    # -------------------------
    gold:
      provider:
        name: yahoo
        code: GC=F
      region: GLOBAL
      unit: 100_troy_ounce
      series:
        intraday: intraday
        daily: daily

    wti:
      provider:
        name: yahoo
        code: CL=F
      region: GLOBAL
      unit: barrel
      series:
        intraday: intraday
        daily: daily

    brent:
      provider:
        name: yahoo
        code: BZ=F
      region: GLOBAL
      unit: barrel
      series:
        intraday: intraday
        daily: daily

    # -------------------------
    # EQUITIES
    # -------------------------
    shell:
      symbol: SHEL
      provider:
        name: yahoo
        code: SHEL
      region: GLOBAL
      unit: share
      series:
        intraday: intraday
        daily: daily

    shell_as:
      provider:
        name: yahoo
        code: SHELL.AS
      region: GLOBAL
      unit: share
      series:
        intraday: intraday
        daily: daily

    # -------------------------
    # ETFs / ETCs
    # -------------------------

    # iShares Core Global Aggregate Bonds
    euna:
      provider:
        name: yahoo
        code: EUNA.DE
      region: WORLD
      unit: share
      series:
        intraday: intraday
        daily: daily

    # Xtrackers MSCI World ex USA UCITS
    exus:
      provider:
        name: yahoo
        code: EXUS.DE
      region: WORLD EX US
      unit: share
      series:
        intraday: intraday
        daily: daily

    # Amundi Euro Govt. Bonds 1-3 yr
    lyq2:
      provider:
        name: yahoo
        code: LYQ2.DE
      region: EUROPE
      unit: share
      series:
        intraday: intraday
        daily: daily

    # iShares Physical Gold ETC
    ppfb:
      provider:
        name: yahoo
        code: PPFB.DE
      region: WORLD
      unit: share
      series:
        intraday: intraday
        daily: daily
    
    # Vanguard Global Aggregate Bonds
    vagf:
      provider:
        name: yahoo
        code: VAGF.DE
      region: WORLD
      unit: share
      series:
        intraday: intraday
        daily: daily
    
    # Vanguard S&P 500 UCITS ETF USD Acc
    vuaa:
      provider:
        name: yahoo
        code: VUAA.DE
      region: US
      unit: share
      series:
        intraday: intraday
        daily: daily

    # Vanguard FTSE All-World UCITS
    vwce:
      provider:
        name: yahoo
        code: VWCE.AS
      region: WORLD
      unit: share
      series:
        intraday: intraday
        daily: daily


    # -------------------------
    # INDEXES
    # -------------------------
    spx:
      provider:
        name: yahoo
        code: ^GSPC
      region: US
      unit: index_point
      series:
        daily: daily

    vix:
      provider:
        name: yahoo
        code: ^VIX
      region: US
      unit: index_point
      series:
        daily: daily

    # -------------------------
    # CRYPTO
    # -------------------------
    bitcoin:
      provider:
        name: yahoo
        code: "BTC-USD"
      symbol: BTCUSD
      region: GLOBAL
      unit: coin
      series:
        intraday: intraday
        daily: daily

    # -------------------------
    # MACRO (FRED + Treasury)
    # -------------------------
    fred_10y_nominal:
      provider: 
        name: fred
        code: DGS10
      symbol: 10Y_NOMINAL
      metadata: us_treasury
      tags:
        instrument: macro
        region: US
        unit: percent
      series:
        daily: [daily, value]

    fred_10y_breakeven:
      provider:
        name: fred
        code: T10YIE
      symbol: 10Y_BREAKEVEN
      metadata: us_treasury
      tags:
        instrument: macro
        region: US
        unit: percent
      series:
        daily: [daily, value]

    fed_balance_sheet:
      provider:
        name: fred
        code: WALCL
      symbol: BALANCE_SHEET
      metadata: us_treasury
      tags:
        instrument: macro
        region: US
        unit: billions_usd
      series:
        daily: [daily, value]

   # CO: treasury_avg:
   # CO:   provider: treasury
   # CO:   provider_code: avg_interest_rate
   # CO:   symbol: AVG_INTEREST_RATE
   # CO:   tags:
   # CO:     instrument: macro
   # CO:     region: US
   # CO:     unit: percent
   # CO:     provider: treasury
   # CO:   series:
   # CO:     daily:
   # CO:       interval: 1d

  # -------------------------
  # COMPOSITES
  # note: disabled in V1
  # -------------------------
  composites:
    10Y_REAL:
      expression: "fred_10y_nominal - fred_10y_breakeven"
      symbol: 10Y_REAL
      series: daily
      tags:
        instrument: macro
        region: US
        unit: percent

    GOLD_DAILY_RANGE:
      expression: "gold.high - gold.low"
      symbol: GOLD_DAILY_RANGE
      series: daily
      tags:
        instrument: commodity
        region: GLOBAL
        unit: USD
