# Copyright 2026 Rik Essenius
# Licensed under the Apache License, Version 2.0. See the LICENSE file for details.
# File: config_test.yaml

environment:
  logging:
    level: debug
  paths:
    wal: wal.jsonl
  timescaledb:
    host: localhost
    port: 5433
    ssl_mode: verify-full
    db: test
    max_batch_size: 1000
    max_batch_age_seconds: 2.0

business:
  providers:
    yahoo:
      timeout: 10s
      # CO: timezone: UTC
      sweep: 
        default: 
          window: 2h
          cadence: 30m
        1d: 
          window: 1w
          cadence: 1d
      constraints:
        history_limits:
          default: 1w
          5m: 60d
          1h: 730d
          1d: null
    
    ecb:
      timeout: 20s
      # CO: timezone: Europe/Berlin
      overlap:
        default:
          window: 0
      constraints: {}

    fred:
      timeout: 10s
      # CO: timezone: America/Chicago
      sweep: 
        default: 
          window: 30d
          cadence: 1w
      constraints: 
        rate_limit:
          # not used as way beyond usage, just capturing 
          requests_per_minute: 120

  
  series_templates:

    daily:
      interval: 1d
      # default puplication_offset is same as interval
      # for >=1d, default retention is long lived, bootstrap_history 10y
      # long lived means stored in table without retention policy

    intraday:
      interval: 5m
      # retention period is defined in the database. Keep aligned.
      retention_period: 30d
      # for <1d, default retention is short lived, bootstrap_history 30d
      # short lived means stored in table with retention policy

    candle: {}
      # default series_type is candle

    value:
      series_type: value
      # values are usually published entities like the daily EUR/USR rate of ECB or FRED interest rates.
      # So, we don't need to wait for the next day to fetch them.

    # Calendar templates. 
    # Default: week_start=mon, week_end=fri, timezone UTC, market open min, market_close max (i.e. 24x5)

    24x7:
      week_start: sun
      week_end: sat

    24x5: {}
      # defaults are correct

    eu_equities:
      timezone: Europe/Amsterdam
      # if used without quotes, yaml converts this to a sexagesimal number.
      # As that is ambiguous betweeh hh:mm:ss (hour*3600+minutes*60+seconds) 
      # and hh:mm (hours*60+minutes), only hh:mm is supported here,
      # since for open and close times, seconds are not likely to be needed.
      # if you need hh:mm:ss nonetheless, put it in quotes: "09:30:25"
      market_open: 09:00
      market_close: 17:30

    us_equities:
      timezone: America/New_York
      market_open: 09:30
      market_close: 16:00

    cboe_equities:
      timezone: America/Chicago
      market_open: 08:30
      market_close: 15:00

    cme_futures:
      timezone: America/Chicago
      market_open: 17:00
      market_close: 16:00  # next day, with daily maintenance break

    us_treasury:
      timezone: America/New_York

    us_commodities:
      timezone: America/New_York
      week_start: sun
      week_end: sat

    new_york:
      timezone: America/New_York
    
    london:
      timezone: Europe/London

    ecb:
      timezone: Europe/Berlin
      publication_offset: 16h
      market_open: 15:55
      market_close: 16:05

  assets:

    # -------------------------
    # FOREX: EURUSD (Yahoo)
    # -------------------------
    eurusd_yahoo:
      provider: 
        name: yahoo
        code: EURUSD=X
      symbol: EURUSD
      tags:
        instrument: forex
        exchange: FOREX
        region: GLOBAL
        currency: USD
        unit: ratio
      series:
        daily: [daily, 24x5, london]

    # -------------------------
    # FOREX: EURUSD (ECB)
    # -------------------------
    eurusd_ecb:
      provider:
        name: ecb
        code: USD_EUR
      symbol: EURUSD
      tags:
        instrument: forex
        exchange: FOREX
        region: EU
        currency: USD
        unit: ratio
      series:
        daily: [daily, value, ecb]

    # -------------------------
    # COMMODITIES
    # -------------------------
    gold:
      provider:
        name: yahoo
        code: GC=F
      symbol: GOLD
      tags:
        instrument: commodity
        exchange: COMMODITY
        region: GLOBAL
        currency: USD
        unit: 100_troy_ounce
      series:
        intraday: [intraday, us_commodities]
        daily: [daily, us_commodities]

    wti:
      provider:
        name: yahoo
        code: CL=F
      symbol: WTI
      tags:
        instrument: commodity
        exchange: COMMODITY
        region: GLOBAL
        currency: USD
        unit: barrel
      series:
        intraday: [intraday, us_commodities]
        daily: [daily, us_commodities]

    brent:
      provider:
        name: yahoo
        code: BZ=F
      symbol: BRENT
      tags:
        instrument: commodity
        exchange: COMMODITY
        region: GLOBAL
        currency: USD
        unit: barrel
      series:
        intraday: [intraday, us_commodities]
        daily: [daily, us_commodities]

    # -------------------------
    # EQUITIES
    # -------------------------
    shell:
      symbol: SHEL
      provider:
        name: yahoo
        code: SHEL
      tags:
        instrument: equity
        exchange: NYSE
        region: GLOBAL
        currency: USD
        unit: share
      series:
        intraday: [intraday, us_equities]
        daily: [daily, us_equities]

    shell_as:
      provider:
        name: yahoo
        code: SHELL.AS
      symbol: SHELL.AS
      tags:
        instrument: equity
        exchange: EURONEXT
        region: GLOBAL
        currency: EUR
        unit: share
      series:
        intraday: [intraday, eu_equities]
        daily: [daily, eu_equities]

    # -------------------------
    # ETFs
    # -------------------------

    vwce:
      provider:
        name: yahoo
        code: VWCE.AS
      symbol: VWCE
      long_name: Vanguard FTSE All-World UCITS ETF USD Acc
      first_trade_date: 2019-07-23
      tags:
        instrument: ETF
        exchange: AMS
        region: WORLD
        currency: EUR
        unit: share
      series:
        intraday: [intraday, eu_equities]
        daily: [daily, eu_equities]

    # -------------------------
    # INDEXES
    # -------------------------
    spx:
      provider:
        name: yahoo
        code: ^GSPC
      symbol: SPX
      tags:
        instrument: index
        exchange: NYSE
        region: US
        currency: USD
        unit: index_point
      series:
        daily: [daily, us_equities]

    vix:
      provider:
        name: yahoo
        code: ^VIX
      symbol: VIX
      tags:
        instrument: index
        exchange: CBOE
        region: US
        currency: USD
        unit: index_point
      series:
        daily: [daily, cboe_equities]

    # -------------------------
    # CRYPTO
    # -------------------------
    bitcoin:
      provider:
        name: yahoo
        code: "BTC-USD"
      symbol: BTCUSD
      tags:
        instrument: crypto
        exchange: CRYPTO
        region: GLOBAL
        currency: USD
        unit: coin
      series:
        intraday: [intraday, 24x7]
        daily: [daily, 24x7]

    # -------------------------
    # MACRO (FRED + Treasury)
    # -------------------------
    fred_10y_nominal:
      provider: 
        name: fred
        code: DGS10
      symbol: 10Y_NOMINAL
      tags:
        instrument: macro
        region: US
        unit: percent
      series:
        daily: [daily, value]

    fred_10y_breakeven:
      provider:
        name: fred
        code: T10YIE
      symbol: 10Y_BREAKEVEN
      tags:
        instrument: macro
        region: US
        unit: percent
      series:
        daily: [daily, value, us_treasury]

    fed_balance_sheet:
      provider:
        name: fred
        code: WALCL
      symbol: BALANCE_SHEET
      tags:
        instrument: macro
        region: US
        unit: billions_usd
      series:
        daily: [daily, value, us_treasury]

   # CO: treasury_avg:
   # CO:   provider: treasury
   # CO:   provider_code: avg_interest_rate
   # CO:   symbol: AVG_INTEREST_RATE
   # CO:   tags:
   # CO:     instrument: macro
   # CO:     region: US
   # CO:     unit: percent
   # CO:     provider: treasury
   # CO:   series:
   # CO:     daily:
   # CO:       interval: 1d

  # -------------------------
  # COMPOSITES
  # note: disabled in V1
  # -------------------------
  composites:
    10Y_REAL:
      expression: "fred_10y_nominal - fred_10y_breakeven"
      symbol: 10Y_REAL
      series: daily
      tags:
        instrument: macro
        region: US
        unit: percent

    GOLD_DAILY_RANGE:
      expression: "gold.high - gold.low"
      symbol: GOLD_DAILY_RANGE
      series: daily
      tags:
        instrument: commodity
        region: GLOBAL
        unit: USD
