# Copyright 2026 Rik Essenius
# Licensed under the Apache License, Version 2.0. See the LICENSE file for details.
# File: config_test.yaml

environment:
  logging:
    level: info
  paths:
    wal: wal.jsonl
    state: state.json
  timescaledb:
    host: localhost
    port: 5432
    ssl_mode: verify-full
    db: test
    max_batch_size: 1000
    max_batch_age_seconds: 2.0

business:
  providers:
    yahoo:
      timeout: 10s
      timezone: UTC
      intraday_history_limit: 5d
      daily_history_limit: 10y
      daily_series_type: candle
    
    ecb:
      timeout: 20s
      timezone: Europe/Berlin
      daily_series_type: value
    
    fred:
      timeout: 10s
      timezone: America/Chicago
      daily_series_type: value

  assets:

    # -------------------------
    # FOREX: EURUSD (Yahoo)
    # -------------------------
    eurusd_yahoo:
      provider: yahoo
      provider_code: EURUSD=X
      symbol: EURUSD
      tags:
        instrument: forex
        exchange: FOREX
        region: GLOBAL
        currency: USD
        unit: ratio
      resolution:
        intraday: {}
        daily: {}

    # -------------------------
    # FOREX: EURUSD (ECB)
    # -------------------------
    eurusd_ecb:
      provider: ecb
      provider_code: USD_EUR
      symbol: EURUSD
      tags:
        instrument: forex
        exchange: FOREX
        region: EU
        currency: USD
        unit: ratio
      resolution:
        daily: {}

    # -------------------------
    # COMMODITIES
    # -------------------------
    gold:
      provider: yahoo
      provider_code: GC=F
      symbol: GOLD
      tags:
        instrument: commodity
        exchange: COMMODITY
        region: GLOBAL
        currency: USD
        unit: ounce
      resolution:
        intraday: {}
        daily: {}

    wti:
      provider: yahoo
      provider_code: CL=F
      symbol: WTI
      tags:
        instrument: commodity
        exchange: COMMODITY
        region: GLOBAL
        currency: USD
        unit: USD
      resolution:
        intraday:
          interval: 10m
        daily:
          interval: 1d

    brent:
      provider: yahoo
      provider_code: BZ=F
      symbol: BRENT
      tags:
        instrument: commodity
        exchange: COMMODITY
        region: GLOBAL
        currency: USD
        unit: USD
      resolution:
        intraday: {}
        daily: {}

    # -------------------------
    # EQUITIES
    # -------------------------
    shell:
      provider: yahoo
      provider_code: SHEL
      symbol: SHEL
      tags:
        instrument: equity
        exchange: NYSE
        region: GLOBAL
        currency: USD
        unit: USD
      resolution:
        daily: {}
        intraday: {}

    shell_as:
      provider: yahoo
      provider_code: SHELL.AS
      symbol: SHELL.AS
      tags:
        instrument: equity
        exchange: EURONEXT
        region: GLOBAL
        currency: EUR
        unit: EUR
      resolution:
        daily: {}
        intraday: {}

    # -------------------------
    # INDEXES
    # -------------------------
    spx:
      provider: yahoo
      provider_code: ^GSPC
      symbol: SPX
      tags:
        instrument: index
        exchange: NYSE
        region: US
        currency: USD
        unit: index
      resolution:
        daily: {}

    vix:
      provider: yahoo
      provider_code: ^VIX
      symbol: VIX
      tags:
        instrument: index
        exchange: CBOE
        region: US
        currency: USD
        unit: index
      resolution:
        daily: {}

    # -------------------------
    # CRYPTO
    # -------------------------
    bitcoin:
      provider: yahoo
      provider_code: "BTC-USD"
      symbol: BTCUSD
      tags:
        instrument: crypto
        exchange: CRYPTO
        region: GLOBAL
        currency: USD
        unit: USD
      resolution:
        intraday: {}
        daily: {}

    # -------------------------
    # MACRO (FRED + Treasury)
    # -------------------------
    fred_10y_nominal:
      provider: fred
      provider_code: DGS10
      symbol: 10Y_NOMINAL
      tags:
        instrument: macro
        region: US
        unit: percent
      resolution:
        daily: {}

    fred_10y_breakeven:
      provider: fred
      provider_code: T10YIE
      symbol: 10Y_BREAKEVEN
      tags:
        instrument: macro
        region: US
        unit: percent
        provider: fred
      resolution:
        daily: {}

    fed_balance_sheet:
      provider: fred
      provider_code: WALCL
      symbol: BALANCE_SHEET
      tags:
        instrument: macro
        region: US
        unit: billions_usd
        provider: fred
      resolution:
        daily: {}

   # treasury_avg:
   #   provider: treasury
   #   provider_code: avg_interest_rate
   #   symbol: AVG_INTEREST_RATE
   #   tags:
   #     instrument: macro
   #     region: US
   #     unit: percent
   #     provider: treasury
   #   resolution:
   #     daily:
   #       interval: 1d

  # -------------------------
  # COMPOSITES
  # -------------------------
  composites:
    10Y_REAL:
      expression: "fred_10y_nominal - fred_10y_breakeven"
      symbol: 10Y_REAL
      resolution: daily
      tags:
        instrument: macro
        region: US
        unit: percent

    GOLD_DAILY_RANGE:
      expression: "gold.high - gold.low"
      symbol: GOLD_DAILY_RANGE
      resolution: daily
      tags:
        instrument: commodity
        region: GLOBAL
        unit: USD
