# Copyright 2026 Rik Essenius
# Licensed under the Apache License, Version 2.0. See the LICENSE file for details.
# File: pytest.ini

[pytest]
pythonpath = .
addopts =
    --cov=finance
    --cov=tools
    --cov-report=term-missing
    --cov-branch
    --cov-fail-under=99
