# Copyright 2026 Rik Essenius
# Licensed under the Apache License, Version 2.0. See the LICENSE file for details.
# File: ops/config.yaml


environment:
  logging:
    level: info
  paths:
    wal: wal.jsonl
    state: state.json
  timescaledb:
    host: localhost
    port: 5432
    ssl_mode: verify-ca
    db: test
    max_batch_size: 1
    max_batch_age_seconds: 1.0

business:
  providers:
    yahoo:
      timeout: 10s
      timezone: UTC
      constraints:
        history_limits:
          default: 7d
          5m: 60d
          1h: 730d
          1d: null
    
    ecb:
      timeout: 20s
      timezone: Europe/Berlin
      constraints: {}
    
  series_templates:
    daily_value:
      interval: 1d
      series_type: value

    daily_candle:
      interval: 1d

    intraday_value:
      interval: 5m
      series_type: value

    intraday_candle:
      interval: 5m

  assets:
    eurusd_yahoo:
      provider: 
        name: yahoo
        code: EURUSD=X
      symbol: EURUSD
      tags:
        instrument: forex
        exchange: FOREX
        region: GLOBAL
        currency: USD
        unit: ratio
      series:
        intraday: intraday_candle
        daily: daily_candle

    eurusd_ecb:
      provider: 
        name: ecb
        code: USD_EUR
      symbol: EURUSD
      tags:
        instrument: forex
        exchange: FOREX
        region: EU
        currency: USD
        unit: ratio
      series:
        daily: daily_value
