# Copyright 2026 Rik Essenius
# Licensed under the Apache License, Version 2.0. See the LICENSE file for details.
# File: ops/config.yaml


environment:
  logging:
    level: info
  paths:
    wal: wal.jsonl
    state: state.json
  timescaledb:
    host: pironman5
    port: 5432
    ssl_mode: verify-ca
    ssl_root_cert: /opt/home-automation/certs/ca-all.crt
    db: test
    max_batch_size: 1
    max_batch_age_seconds: 1.0

business:
  providers:
    yahoo:
      timezone: UTC
      intraday_history_limit: 5d
      daily_history_limit: 10y
      daily_series_type: candle
    
    ecb:
      timezone: Europe/Berlin
      daily_series_type: value
    
    fred:
      timezone: America/Chicago
      daily_series_type: value

  assets:

    eurusd:
      provider: yahoo
      provider_code: EURUSD=X
      display_name: Euro-USD rate
      tags:
        instrument: forex
        exchange: FOREX
        region: GLOBAL
        currency: USD
        unit: ratio
      resolution:
        daily: {}
